# Soil Temperature Prediction at different depths

## 1. Data Preprocessing Step

In [1]:
# Import the necessary python libraries such as pandas, numpy, matplotlib, scikit-learn for data analysis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Regression of the Soil Temperature at depth of 100cm

## Step 1: Getting the data ready for the machine learning modelling

### Main data cleaning and preprocessing activities
### 1. Reading the dataset from file using pandas function
### 2. Split the dataset in to features (independent variable) and labels(dependent variable)
### 3. Imputing (filling) or disregarding missing values depending on the feature or label type
### 4. Encoding or converting non-numerical values to numeric values if required ( Feature encoding)
### 5. Reduce data if it is heavy for the machine to process

In [2]:
# 1. Get the data from the original csv file from data folder
dataset = pd.read_csv("data/NMBUDatasetFinal.csv")
dataset

,year,month,date,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,...,mean_wind_speed_10m_m_s,max_wind_speed_10_m_s,wind_direction_10m,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm,target_soil_temperature_100cm
0,2018,1,1,3.2,0.7,4.4,-0.1,0.1,0.1,0.5,...,2.6,4.7,S,0.13,0.45,-0.12,NaN,2.3,5.0,2.9
1,2018,1,2,-1.9,-5.7,1.4,0.0,0.1,0.1,0.5,...,NaN,NaN,NaN,-1.67,0.32,-0.13,NaN,0.0,3.0,2.9
2,2018,1,3,-0.4,-6.4,1.3,-0.1,0.1,0.1,0.5,...,NaN,NaN,NaN,-0.98,0.43,-0.23,NaN,3.4,3.0,2.9
3,2018,1,4,0.7,0.2,1.1,0.0,0.1,0.1,0.5,...,4.1,5.4,N,-1.31,0.59,-0.12,NaN,2.5,4.0,2.9
4,2018,1,5,-1.8,-5.5,0.1,0.0,0.1,0.1,0.5,...,3.9,5.7,N,-1.65,0.71,-0.11,NaN,1.4,5.0,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,2022,12,27,-1.7,-8.2,1.0,-0.1,0.2,0.1,0.4,...,2.4,5.7,S,-2.06,0.44,-0.29,NaN,0.0,9.0,3.6
1822,2022,12,28,-5.5,-8.9,-4.1,0.0,0.2,0.1,0.5,...,2.0,3.8,N,-1.05,0.88,-0.32,NaN,0.5,9.0,3.5
1823,2022,12,29,0.7,-4.4,4.1,-0.1,0.1,0.1,0.5,...,2.7,6.9,S,-1.23,0.70,-0.33,NaN,8.3,12.0,3.5
1824,2022,12,30,2.7,0.3,4.5,-0.1,0.1,0.1,0.5,...,4.2,8.6,S,-1.66,0.59,-0.31,NaN,6.6,6.0,3.4
1825,2022,12,31,3.0,-3.2,5.6,0.0,0.2,0.1,0.5,...,5.4,11.8,S,-4.34,0.26,-0.27,NaN,4.9,1.0,3.4

In [3]:
len(dataset)

1826

In [16]:
# Check rows with empty values
rows_with_empty_values = dataset[dataset.isna().any(axis=1)]
rows_with_empty_values

,year,month,date,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,...,mean_wind_speed_10m_m_s,max_wind_speed_10_m_s,wind_direction_10m,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm,target_soil_temperature_100cm
0,2018,1,1,3.2,0.7,4.4,-0.1,0.1,0.1,0.5,...,2.6,4.7,S,0.13,0.45,-0.12,NaN,2.3,5.0,2.9
1,2018,1,2,-1.9,-5.7,1.4,0.0,0.1,0.1,0.5,...,NaN,NaN,NaN,-1.67,0.32,-0.13,NaN,0.0,3.0,2.9
2,2018,1,3,-0.4,-6.4,1.3,-0.1,0.1,0.1,0.5,...,NaN,NaN,NaN,-0.98,0.43,-0.23,NaN,3.4,3.0,2.9
3,2018,1,4,0.7,0.2,1.1,0.0,0.1,0.1,0.5,...,4.1,5.4,N,-1.31,0.59,-0.12,NaN,2.5,4.0,2.9
4,2018,1,5,-1.8,-5.5,0.1,0.0,0.1,0.1,0.5,...,3.9,5.7,N,-1.65,0.71,-0.11,NaN,1.4,5.0,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,2022,12,27,-1.7,-8.2,1.0,-0.1,0.2,0.1,0.4,...,2.4,5.7,S,-2.06,0.44,-0.29,NaN,0.0,9.0,3.6
1822,2022,12,28,-5.5,-8.9,-4.1,0.0,0.2,0.1,0.5,...,2.0,3.8,N,-1.05,0.88,-0.32,NaN,0.5,9.0,3.5
1823,2022,12,29,0.7,-4.4,4.1,-0.1,0.1,0.1,0.5,...,2.7,6.9,S,-1.23,0.70,-0.33,NaN,8.3,12.0,3.5
1824,2022,12,30,2.7,0.3,4.5,-0.1,0.1,0.1,0.5,...,4.2,8.6,S,-1.66,0.59,-0.31,NaN,6.6,6.0,3.4
1825,2022,12,31,3.0,-3.2,5.6,0.0,0.2,0.1,0.5,...,5.4,11.8,S,-4.34,0.26,-0.27,NaN,4.9,1.0,3.4

In [18]:
# Check rows with non-empty values throughout its columns
rows_with_non_empty_values = dataset[dataset.notna().all(axis=1)]
rows_with_non_empty_values

,year,month,date,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,...,mean_wind_speed_10m_m_s,max_wind_speed_10_m_s,wind_direction_10m,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm,target_soil_temperature_100cm
123,2018,5,4,7.5,0.2,13.7,7.5,7.3,6.8,6.4,...,2.4,5.7,S,6.89,0.21,0.98,0.3,0.0,0.0,4.2
124,2018,5,5,11.5,6.3,17.8,9.5,8.9,8.1,7.1,...,3.3,6.7,S,9.69,0.22,1.75,1.4,0.0,0.0,4.3
125,2018,5,6,12.3,6.6,18.0,10.1,9.7,9.0,8.0,...,3.8,7.1,S,8.62,0.22,1.27,2.7,0.0,0.0,4.5
126,2018,5,7,12.9,5.7,19.5,10.4,10.0,9.4,8.5,...,2.9,5.7,S,8.51,0.22,1.17,2.5,0.0,0.0,4.7
127,2018,5,8,14.4,7.7,21.0,11.2,10.7,10.0,9.0,...,2.4,7.1,S,9.95,0.23,1.44,3.1,0.0,0.0,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1739,2022,10,6,11.1,8.6,14.6,10.8,10.9,10.8,10.8,...,4.4,8.3,SW,-0.36,0.22,-0.37,1.6,0.0,0.0,10.9
1740,2022,10,7,12.1,9.9,14.9,10.7,10.8,10.6,10.7,...,5.9,9.2,S,-0.55,0.19,0.03,1.6,3.6,0.0,10.9
1741,2022,10,8,9.2,4.6,13.4,9.9,10.3,10.3,10.6,...,2.6,4.8,W,-0.08,0.25,-0.74,1.9,0.0,0.0,10.9
1742,2022,10,9,8.5,1.5,13.5,8.9,9.2,9.3,10.0,...,3.6,7.8,S,1.07,0.25,-0.56,1.1,0.5,0.0,10.9
1743,2022,10,10,10.2,3.8,12.6,9.9,10.0,9.9,10.0,...,4.4,7.5,S,-0.49,0.19,-0.15,0.5,0.9,0.0,10.9

In [ ]:
dataset.dtypes

In [5]:
# 2. Split the dataset in to features (independent variables) and labels(dependent variable = target_soil_temperature_100cm )
X = dataset.drop("target_soil_temperature_100cm", axis =1) # Features
Y = dataset["target_soil_temperature_100cm"]

In [6]:
# Check the features dataset
X

,year,month,date,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,...,air_pressure__2m_mbar,mean_wind_speed_10m_m_s,max_wind_speed_10_m_s,wind_direction_10m,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm
0,2018,1,1,3.2,0.7,4.4,-0.1,0.1,0.1,0.5,...,972.3,2.6,4.7,S,0.13,0.45,-0.12,NaN,2.3,5.0
1,2018,1,2,-1.9,-5.7,1.4,0.0,0.1,0.1,0.5,...,982.1,NaN,NaN,NaN,-1.67,0.32,-0.13,NaN,0.0,3.0
2,2018,1,3,-0.4,-6.4,1.3,-0.1,0.1,0.1,0.5,...,978.0,NaN,NaN,NaN,-0.98,0.43,-0.23,NaN,3.4,3.0
3,2018,1,4,0.7,0.2,1.1,0.0,0.1,0.1,0.5,...,978.8,4.1,5.4,N,-1.31,0.59,-0.12,NaN,2.5,4.0
4,2018,1,5,-1.8,-5.5,0.1,0.0,0.1,0.1,0.5,...,982.0,3.9,5.7,N,-1.65,0.71,-0.11,NaN,1.4,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,2022,12,27,-1.7,-8.2,1.0,-0.1,0.2,0.1,0.4,...,990.6,2.4,5.7,S,-2.06,0.44,-0.29,NaN,0.0,9.0
1822,2022,12,28,-5.5,-8.9,-4.1,0.0,0.2,0.1,0.5,...,992.0,2.0,3.8,N,-1.05,0.88,-0.32,NaN,0.5,9.0
1823,2022,12,29,0.7,-4.4,4.1,-0.1,0.1,0.1,0.5,...,975.3,2.7,6.9,S,-1.23,0.70,-0.33,NaN,8.3,12.0
1824,2022,12,30,2.7,0.3,4.5,-0.1,0.1,0.1,0.5,...,979.9,4.2,8.6,S,-1.66,0.59,-0.31,NaN,6.6,6.0
1825,2022,12,31,3.0,-3.2,5.6,0.0,0.2,0.1,0.5,...,975.9,5.4,11.8,S,-4.34,0.26,-0.27,NaN,4.9,1.0

In [7]:
# Check the label dataset
Y

0       2.9
1       2.9
2       2.9
3       2.9
4       2.8
       ...
1821    3.6
1822    3.5
1823    3.5
1824    3.4
1825    3.4
Name: target_soil_temperature_100cm, Length: 1826, dtype: float64

In [8]:
# 3. Filling or disregarding missing values 
# First check the missing columns and the number of missing values in each column
missing_values = dataset.isna().sum()
missing_values

year                                0
month                               0
date                                0
mean_air_temperature_2m             0
min_air_temperature_2m              0
max_air_temperature_2m              0
soil_temperature_2cm                7
soil_temperature_5cm                5
soil_temperature_10cm               5
soil_temperature_20cm               5
soil_temperature_50cm               5
relative_humidity_%                23
air_pressure__2m_mbar               5
mean_wind_speed_10m_m_s            57
max_wind_speed_10_m_s              42
wind_direction_10m                 43
radiation_balance_w_m2              5
albedo_RR_GR                       28
earth_heat_flux_MJ_m2              19
evaporation_mm                   1013
rainfall_mm                         4
snowfall_cm                       542
target_soil_temperature_100cm       5
dtype: int64

### The missing values of the snowfall are in all seasons except winter so you can fill them zero
### The missing values of the evaporation are due to the measurement not taken from November to March in winter, so you can fill them by zero.
### The few missing values on soil temperatures at different depth are due to missing measurements and a mean approximate value can be taken
### The few missing values on relative humidity, air pressure, radiation, heat flux and rainfall are due to missing measurements and mean value can be taken
### Fill empty values by either the average value or zero depending on the feature type

In [9]:
# 3. Filling or disregarding missing values contd'

X["evaporation_mm"] = X["evaporation_mm"].fillna(0.0)
X["soil_temperature_2cm"] = X["soil_temperature_2cm"].fillna(X["soil_temperature_2cm"].mean())
X["soil_temperature_5cm"] = X["soil_temperature_5cm"].fillna(X["soil_temperature_5cm"].mean())
X["soil_temperature_10cm"] = X["soil_temperature_10cm"].fillna(X["soil_temperature_10cm"].mean())
X["soil_temperature_20cm"] = X["soil_temperature_20cm"].fillna(X["soil_temperature_20cm"].mean())
X["soil_temperature_20cm"] = X["soil_temperature_20cm"].fillna(X["soil_temperature_20cm"].mean())
X["soil_temperature_50cm"] = X["soil_temperature_50cm"].fillna(X["soil_temperature_50cm"].mean())
X["relative_humidity_%"] = X["relative_humidity_%"].fillna(X["relative_humidity_%"].mean())
X["air_pressure__2m_mbar"] = X["air_pressure__2m_mbar"].fillna(X["air_pressure__2m_mbar"].mean())
X["radiation_balance_w_m2"] = X["radiation_balance_w_m2"].fillna(X["radiation_balance_w_m2"].mean())
X["albedo_RR_GR"] = X["albedo_RR_GR"].fillna(X["albedo_RR_GR"].mean())
X["earth_heat_flux_MJ_m2"] = X["earth_heat_flux_MJ_m2"].fillna(X["earth_heat_flux_MJ_m2"].mean())
X["rainfall_mm"] = X["rainfall_mm"].fillna(X["rainfall_mm"].mean())
X["snowfall_cm"] = X["snowfall_cm"].fillna(0.0)
Y.fillna(Y.mean(), inplace=True)

# To drop missing values in a column
# X.dropna(subset=["evaporation_mm"], inplace=True)

# To fill missing values with sckit-learn
# from sklearn.impute import SimpleImputer
# from sklearn.compose import ColumnTransformer
# Fill the categorical values with missing and numerical values with mean
# cat_imputer = SimpleImputer(strategy="constant, fill_value="missing")
# column_name_imputer = SimpleImputer(strategy = "constant", fill_value=4)
# num_imputer = SimpleImputer(strategy ="mean")
# Define columns
# cat_features =["evaporation", "wind_speed"]
# column_name_features = ["column_name"]
# num_features= ["num_column"]
# Create an imputer something that fills missing data
# imputer = ColumnTransformer([("cat_imputer", cat_imputer, cat_features),("column_name_imputer", column_name_imputer, column_name_features),("num_imputer", num_imputer, num_features)])
# Transform the data
# filled_X = imputer.fit_transform(X)

In [10]:
# Check missing values on the features after filling or disregarding values
X.isna().sum()

year                        0
month                       0
date                        0
mean_air_temperature_2m     0
min_air_temperature_2m      0
max_air_temperature_2m      0
soil_temperature_2cm        0
soil_temperature_5cm        0
soil_temperature_10cm       0
soil_temperature_20cm       0
soil_temperature_50cm       0
relative_humidity_%         0
air_pressure__2m_mbar       0
mean_wind_speed_10m_m_s    57
max_wind_speed_10_m_s      42
wind_direction_10m         43
radiation_balance_w_m2      0
albedo_RR_GR                0
earth_heat_flux_MJ_m2       0
evaporation_mm              0
rainfall_mm                 0
snowfall_cm                 0
dtype: int64

In [11]:
# Check missing values on the label after filling or disregarding values
Y.isna().sum()

0

In [12]:
# Remove the unnecessary columns from the features dataset
columns_to_drop = ['mean_wind_speed_10m_m_s', 'max_wind_speed_10_m_s', 'wind_direction_10m']  # List of column names to drop
X.drop(columns=columns_to_drop, axis=1, inplace=True)
X

,year,month,date,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,soil_temperature_50cm,relative_humidity_%,air_pressure__2m_mbar,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm
0,2018,1,1,3.2,0.7,4.4,-0.1,0.1,0.1,0.5,1.3,100.0,972.3,0.13,0.45,-0.12,0.0,2.3,5.0
1,2018,1,2,-1.9,-5.7,1.4,0.0,0.1,0.1,0.5,1.3,100.0,982.1,-1.67,0.32,-0.13,0.0,0.0,3.0
2,2018,1,3,-0.4,-6.4,1.3,-0.1,0.1,0.1,0.5,1.3,99.0,978.0,-0.98,0.43,-0.23,0.0,3.4,3.0
3,2018,1,4,0.7,0.2,1.1,0.0,0.1,0.1,0.5,1.3,96.0,978.8,-1.31,0.59,-0.12,0.0,2.5,4.0
4,2018,1,5,-1.8,-5.5,0.1,0.0,0.1,0.1,0.5,1.3,86.0,982.0,-1.65,0.71,-0.11,0.0,1.4,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,2022,12,27,-1.7,-8.2,1.0,-0.1,0.2,0.1,0.4,1.4,86.0,990.6,-2.06,0.44,-0.29,0.0,0.0,9.0
1822,2022,12,28,-5.5,-8.9,-4.1,0.0,0.2,0.1,0.5,1.4,90.0,992.0,-1.05,0.88,-0.32,0.0,0.5,9.0
1823,2022,12,29,0.7,-4.4,4.1,-0.1,0.1,0.1,0.5,1.4,95.0,975.3,-1.23,0.70,-0.33,0.0,8.3,12.0
1824,2022,12,30,2.7,0.3,4.5,-0.1,0.1,0.1,0.5,1.4,92.0,979.9,-1.66,0.59,-0.31,0.0,6.6,6.0
1825,2022,12,31,3.0,-3.2,5.6,0.0,0.2,0.1,0.5,1.4,83.0,975.9,-4.34,0.26,-0.27,0.0,4.9,1.0

In [13]:
# 5. Encoding non-numeric values
# The only non-numeric value in our dataset is the Wind Direction but it is already removed in the previous steps
# as it is not critical parameter for soil temperature estimation but if required use the following code to
# convert it to degress
# Change the wind direction from N/NE/E/SE/S/SW/W/NW to 0/45/90/135/180/225/270/315 degress

# dataset.loc[dataset['wind_direction_10m'] == 'N', 'wind_direction_10m'] = 0
# dataset.loc[dataset['wind_direction_10m'] == 'NE', 'wind_direction_10m'] = 45
# dataset.loc[dataset['wind_direction_10m'] == 'E', 'wind_direction_10m'] = 90
# dataset.loc[dataset['wind_direction_10m'] == 'SE', 'wind_direction_10m'] = 135
# dataset.loc[dataset['wind_direction_10m'] == 'S', 'wind_direction_10m'] = 180
# dataset.loc[dataset['wind_direction_10m'] == 'SW', 'wind_direction_10m'] = 225
# dataset.loc[dataset['wind_direction_10m'] == 'W', 'wind_direction_10m'] = 270
# dataset.loc[dataset['wind_direction_10m'] == 'NW', 'wind_direction_10m'] = 315

# We could also use OneHotEncoder from sklealrn
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer
# categorical_features = ["wind_direction_10m", "wind_speed_m_s"]
# one_hot = OneHotEncoder()
# transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)]
#                                remainder ="passthrough")
# transformed_X = transformer.fit_transform()
# pd.DataFrame(transformed_X)

In [14]:
# Split the feature and label datasets in to 80/20 training and test datasets respectively
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

In [15]:
# Build the machine learning model
# To start with the common regressor algorithm of Random Forest
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train, Y_train)
model.score(X_test, Y_test)

0.996473002244904

## Dataset taken from all stations in Norway from IMT website

In [112]:
# 1. Get the data from the original csv file from data folder
dataset2 = pd.read_csv("data/IMT_Stations_Data_CSV.csv")
dataset2

,Year,Month,Day,Station,TM_mean_air_temperature_2m_c,TN_min_air_temperature_2m_c,TX_max_air_temperature_2m_c,UM_realtiWe_humudity_%,RR_precipitation_mm,FM2_mean_wind_speed_2m_m_s,...,TJM5_soil_temperature_5cm_c,TJM10_soil_temperature_10cm_c,TJM20_soil_temperature_20cm_c,TJM30_soil_temperature_30cm_c,TJM50_soil_temperature_50cm_c,TJM100_soil_temperature_100cm_c,SS_snowfall_cm,PPP_air_pressure__2m_hPa,EPP_evaporation_mm,VAN20M_volumetric_soil_water_20cm_%
0,2018,1,1,Apelsvoll,-2.1,-5.3,0.6,96.9,1.0,0.4,...,-0.1,0.1,0.5,0.6,1.4,2.7,NaN,NaN,NaN,0.3
1,2018,1,2,Apelsvoll,-3.3,-8.4,0.8,92.1,0.4,1.2,...,-0.1,0.1,0.5,0.6,1.4,2.7,NaN,NaN,NaN,0.3
2,2018,1,3,Apelsvoll,-4.7,-7.1,-2.5,94.8,8.6,0.9,...,-0.1,0.1,0.5,0.6,1.4,2.7,NaN,NaN,NaN,0.3
3,2018,1,4,Apelsvoll,-1.7,-2.6,-1.0,96.3,7.5,0.5,...,-0.1,0.1,0.5,0.6,1.4,2.6,NaN,NaN,NaN,0.3
4,2018,1,5,Apelsvoll,-4.9,-11.4,-1.6,89.3,1.9,1.1,...,-0.1,0.1,0.5,0.6,1.4,2.6,NaN,NaN,NaN,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97982,2022,12,27,Valnesfjord,2.1,-1.5,5.2,60.9,0.0,3.9,...,-0.7,-0.6,-0.3,-0.2,0.4,1.7,NaN,NaN,NaN,NaN
97983,2022,12,28,Valnesfjord,-1.1,-3.6,1.1,75.1,4.3,2.2,...,-0.6,-0.5,-0.3,-0.1,0.4,1.7,NaN,NaN,NaN,NaN
97984,2022,12,29,Valnesfjord,-1.7,-3.7,0.7,54.1,0.1,5.3,...,-0.6,-0.5,-0.3,-0.1,0.4,1.7,NaN,NaN,NaN,NaN
97985,2022,12,30,Valnesfjord,0.6,-0.8,2.4,65.0,0.3,3.7,...,-0.6,-0.5,-0.2,-0.1,0.4,1.7,NaN,NaN,NaN,NaN
97986,2022,12,31,Valnesfjord,2.6,0.2,3.8,72.3,7.1,4.7,...,-0.6,-0.5,-0.2,-0.1,0.4,1.7,NaN,NaN,NaN,NaN

In [113]:
# Check rows with empty values
rows_with_empty_values = dataset2[dataset2.isna().any(axis=1)]
rows_with_empty_values

,Year,Month,Day,Station,TM_mean_air_temperature_2m_c,TN_min_air_temperature_2m_c,TX_max_air_temperature_2m_c,UM_realtiWe_humudity_%,RR_precipitation_mm,FM2_mean_wind_speed_2m_m_s,...,TJM5_soil_temperature_5cm_c,TJM10_soil_temperature_10cm_c,TJM20_soil_temperature_20cm_c,TJM30_soil_temperature_30cm_c,TJM50_soil_temperature_50cm_c,TJM100_soil_temperature_100cm_c,SS_snowfall_cm,PPP_air_pressure__2m_hPa,EPP_evaporation_mm,VAN20M_volumetric_soil_water_20cm_%
0,2018,1,1,Apelsvoll,-2.1,-5.3,0.6,96.9,1.0,0.4,...,-0.1,0.1,0.5,0.6,1.4,2.7,NaN,NaN,NaN,0.3
1,2018,1,2,Apelsvoll,-3.3,-8.4,0.8,92.1,0.4,1.2,...,-0.1,0.1,0.5,0.6,1.4,2.7,NaN,NaN,NaN,0.3
2,2018,1,3,Apelsvoll,-4.7,-7.1,-2.5,94.8,8.6,0.9,...,-0.1,0.1,0.5,0.6,1.4,2.7,NaN,NaN,NaN,0.3
3,2018,1,4,Apelsvoll,-1.7,-2.6,-1.0,96.3,7.5,0.5,...,-0.1,0.1,0.5,0.6,1.4,2.6,NaN,NaN,NaN,0.3
4,2018,1,5,Apelsvoll,-4.9,-11.4,-1.6,89.3,1.9,1.1,...,-0.1,0.1,0.5,0.6,1.4,2.6,NaN,NaN,NaN,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97982,2022,12,27,Valnesfjord,2.1,-1.5,5.2,60.9,0.0,3.9,...,-0.7,-0.6,-0.3,-0.2,0.4,1.7,NaN,NaN,NaN,NaN
97983,2022,12,28,Valnesfjord,-1.1,-3.6,1.1,75.1,4.3,2.2,...,-0.6,-0.5,-0.3,-0.1,0.4,1.7,NaN,NaN,NaN,NaN
97984,2022,12,29,Valnesfjord,-1.7,-3.7,0.7,54.1,0.1,5.3,...,-0.6,-0.5,-0.3,-0.1,0.4,1.7,NaN,NaN,NaN,NaN
97985,2022,12,30,Valnesfjord,0.6,-0.8,2.4,65.0,0.3,3.7,...,-0.6,-0.5,-0.2,-0.1,0.4,1.7,NaN,NaN,NaN,NaN
97986,2022,12,31,Valnesfjord,2.6,0.2,3.8,72.3,7.1,4.7,...,-0.6,-0.5,-0.2,-0.1,0.4,1.7,NaN,NaN,NaN,NaN

In [114]:
# Check rows with non-empty values throughout its columns
rows_with_non_empty_values = dataset2[dataset2.notna().all(axis=1)]
rows_with_non_empty_values

Empty DataFrame
Columns: [Year, Month, Day, Station, TM_mean_air_temperature_2m_c, TN_min_air_temperature_2m_c, TX_max_air_temperature_2m_c, UM_realtiWe_humudity_%, RR_precipitation_mm, FM2_mean_wind_speed_2m_m_s, DM2_wind_direction_2m_degree, Q0_global_radiation_MJ_m^2, TJM1_soil_temperature_1cm_c, TJM5_soil_temperature_5cm_c, TJM10_soil_temperature_10cm_c, TJM20_soil_temperature_20cm_c, TJM30_soil_temperature_30cm_c, TJM50_soil_temperature_50cm_c, TJM100_soil_temperature_100cm_c, SS_snowfall_cm, PPP_air_pressure__2m_hPa, EPP_evaporation_mm, VAN20M_volumetric_soil_water_20cm_%]
Index: []

[0 rows x 23 columns]

In [115]:
# First check the missing columns and the number of missing values in each column
missing_values_new = dataset2.isna().sum()
missing_values_new

Year                                       0
Month                                      0
Day                                        0
Station                                    1
TM_mean_air_temperature_2m_c             692
TN_min_air_temperature_2m_c              691
TX_max_air_temperature_2m_c              688
UM_realtiWe_humudity_%                  3160
RR_precipitation_mm                     3895
FM2_mean_wind_speed_2m_m_s             10096
DM2_wind_direction_2m_degree           96182
Q0_global_radiation_MJ_m^2              7294
TJM1_soil_temperature_1cm_c            54665
TJM5_soil_temperature_5cm_c            62427
TJM10_soil_temperature_10cm_c           9704
TJM20_soil_temperature_20cm_c          12698
TJM30_soil_temperature_30cm_c          66172
TJM50_soil_temperature_50cm_c          66113
TJM100_soil_temperature_100cm_c        66576
SS_snowfall_cm                         97987
PPP_air_pressure__2m_hPa               97987
EPP_evaporation_mm                     48508
VAN20M_volumetric_soil_water_20cm_%    81654
dtype: int64

In [116]:
# Remove rows who have station name empty
dataset2_filtered = dataset2.dropna(subset=['Station'])
dataset2_filtered.dropna(subset=['TM_mean_air_temperature_2m_c'], inplace=True)
dataset2_filtered.dropna(subset=['TN_min_air_temperature_2m_c'], inplace=True)
dataset2_filtered.dropna(subset=['TX_max_air_temperature_2m_c'], inplace=True)
dataset2_filtered.dropna(subset=['UM_realtiWe_humudity_%'], inplace=True)
dataset2_filtered.dropna(subset=['RR_precipitation_mm'], inplace=True)
dataset2_filtered.dropna(subset=['Q0_global_radiation_MJ_m^2'], inplace=True)
dataset2_filtered.dropna(subset=['TJM10_soil_temperature_10cm_c'], inplace=True)
dataset2_filtered.dropna(subset=['TJM20_soil_temperature_20cm_c'], inplace=True)
dataset2_filtered.dropna(subset=['EPP_evaporation_mm'], inplace=True)

C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3176899717.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.dropna(subset=['TM_mean_air_temperature_2m_c'], inplace=True)
C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3176899717.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.dropna(subset=['TN_min_air_temperature_2m_c'], inplace=True)
C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3176899717.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.dropna(subset=['TX_max_air_temperature_2m_c'], inplace=True)
C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3176899717.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.dropna(subset=['UM_realtiWe_humudity_%'], inplace=True)
C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3176899717.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.dropna(subset=['RR_precipitation_mm'], inplace=True)
C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3176899717.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.dropna(subset=['Q0_global_radiation_MJ_m^2'], inplace=True)
C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3176899717.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.dropna(subset=['TJM10_soil_temperature_10cm_c'], inplace=True)
C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3176899717.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.dropna(subset=['TJM20_soil_temperature_20cm_c'], inplace=True)
C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3176899717.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.dropna(subset=['EPP_evaporation_mm'], inplace=True)

In [117]:
missing_values_new = dataset2_filtered.isna().sum()
missing_values_new

Year                                       0
Month                                      0
Day                                        0
Station                                    0
TM_mean_air_temperature_2m_c               0
TN_min_air_temperature_2m_c                0
TX_max_air_temperature_2m_c                0
UM_realtiWe_humudity_%                     0
RR_precipitation_mm                        0
FM2_mean_wind_speed_2m_m_s              3234
DM2_wind_direction_2m_degree           40165
Q0_global_radiation_MJ_m^2                 0
TJM1_soil_temperature_1cm_c            20312
TJM5_soil_temperature_5cm_c            23371
TJM10_soil_temperature_10cm_c              0
TJM20_soil_temperature_20cm_c              0
TJM30_soil_temperature_30cm_c          24163
TJM50_soil_temperature_50cm_c          24162
TJM100_soil_temperature_100cm_c        24473
SS_snowfall_cm                         41229
PPP_air_pressure__2m_hPa               41229
EPP_evaporation_mm                         0
VAN20M_volumetric_soil_water_20cm_%    32723
dtype: int64

## The dataset with non-empty values for variables: date, station, TM_mean_air_temperature_2m_c, TN_min_air_temperature_2m_c, TX_max_air_temperature_2m_c, UM_realtiWe_humudity_%, RR_precipitation_mm, Q0_global_radiation_MJ_m^2, TJM10_soil_temperature_10cm_c, TJM20_soil_temperature_20cm_c, EPP_evaporation_mm

In [118]:
# new filtered dataset
dataset2_filtered.drop("VAN20M_volumetric_soil_water_20cm_%", axis=1, inplace=True)
dataset2_filtered.drop("DM2_wind_direction_2m_degree", axis=1, inplace=True)
dataset2_filtered.to_csv("data/IMT_stations_data_filtered.csv")
dataset2_filtered

C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3808933765.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.drop("VAN20M_volumetric_soil_water_20cm_%", axis=1, inplace=True)
C:\Users\mamda\AppData\Local\Temp\ipykernel_11256\3808933765.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_filtered.drop("DM2_wind_direction_2m_degree", axis=1, inplace=True)

,Year,Month,Day,Station,TM_mean_air_temperature_2m_c,TN_min_air_temperature_2m_c,TX_max_air_temperature_2m_c,UM_realtiWe_humudity_%,RR_precipitation_mm,FM2_mean_wind_speed_2m_m_s,...,TJM1_soil_temperature_1cm_c,TJM5_soil_temperature_5cm_c,TJM10_soil_temperature_10cm_c,TJM20_soil_temperature_20cm_c,TJM30_soil_temperature_30cm_c,TJM50_soil_temperature_50cm_c,TJM100_soil_temperature_100cm_c,SS_snowfall_cm,PPP_air_pressure__2m_hPa,EPP_evaporation_mm
59,2018,3,1,Apelsvoll,-18.1,-22.1,-12.7,67.4,0.0,1.3,...,NaN,0.1,0.2,0.5,0.5,1.1,1.9,NaN,NaN,0.0
60,2018,3,2,Apelsvoll,-13.5,-20.6,-9.6,65.8,0.0,0.9,...,NaN,0.0,0.2,0.5,0.5,1.1,1.9,NaN,NaN,0.0
61,2018,3,3,Apelsvoll,-8.8,-11.0,-4.2,72.8,0.0,0.6,...,NaN,0.0,0.2,0.5,0.5,1.1,1.9,NaN,NaN,0.0
62,2018,3,4,Apelsvoll,-8.0,-10.4,-2.6,79.2,0.4,0.6,...,NaN,0.0,0.1,0.5,0.5,1.1,1.9,NaN,NaN,0.0
63,2018,3,5,Apelsvoll,-7.6,-9.3,-5.1,88.8,2.0,0.7,...,NaN,0.0,0.1,0.5,0.5,1.1,1.9,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97890,2022,9,26,Valnesfjord,11.7,9.5,13.4,61.8,0.5,4.7,...,NaN,9.5,9.7,10.0,10.1,10.1,9.7,NaN,NaN,1.4
97891,2022,9,27,Valnesfjord,10.2,7.0,12.9,64.1,-0.2,3.0,...,NaN,8.6,8.9,9.5,9.7,9.9,9.7,NaN,NaN,1.3
97892,2022,9,28,Valnesfjord,9.6,4.8,13.6,68.7,-0.1,1.6,...,NaN,8.2,8.5,9.0,9.3,9.7,9.6,NaN,NaN,1.0
97893,2022,9,29,Valnesfjord,10.2,8.0,13.0,65.7,0.0,1.8,...,NaN,8.6,8.7,9.0,9.1,9.4,9.5,NaN,NaN,0.8
97894,2022,9,30,Valnesfjord,6.8,1.8,10.5,67.8,0.0,1.1,...,NaN,7.2,7.8,8.6,8.9,9.3,9.4,NaN,NaN,0.9

In [119]:
# Check the rows that has no empty values
non_empty_rows = dataset2_filtered.dropna(how='any')
non_empty_rows

Empty DataFrame
Columns: [Year, Month, Day, Station, TM_mean_air_temperature_2m_c, TN_min_air_temperature_2m_c, TX_max_air_temperature_2m_c, UM_realtiWe_humudity_%, RR_precipitation_mm, FM2_mean_wind_speed_2m_m_s, Q0_global_radiation_MJ_m^2, TJM1_soil_temperature_1cm_c, TJM5_soil_temperature_5cm_c, TJM10_soil_temperature_10cm_c, TJM20_soil_temperature_20cm_c, TJM30_soil_temperature_30cm_c, TJM50_soil_temperature_50cm_c, TJM100_soil_temperature_100cm_c, SS_snowfall_cm, PPP_air_pressure__2m_hPa, EPP_evaporation_mm]
Index: []

[0 rows x 21 columns]

In [120]:
missing_values_new = dataset2_filtered.isna().sum()
missing_values_new

Year                                   0
Month                                  0
Day                                    0
Station                                0
TM_mean_air_temperature_2m_c           0
TN_min_air_temperature_2m_c            0
TX_max_air_temperature_2m_c            0
UM_realtiWe_humudity_%                 0
RR_precipitation_mm                    0
FM2_mean_wind_speed_2m_m_s          3234
Q0_global_radiation_MJ_m^2             0
TJM1_soil_temperature_1cm_c        20312
TJM5_soil_temperature_5cm_c        23371
TJM10_soil_temperature_10cm_c          0
TJM20_soil_temperature_20cm_c          0
TJM30_soil_temperature_30cm_c      24163
TJM50_soil_temperature_50cm_c      24162
TJM100_soil_temperature_100cm_c    24473
SS_snowfall_cm                     41229
PPP_air_pressure__2m_hPa           41229
EPP_evaporation_mm                     0
dtype: int64

In [121]:
# Remove the empty values of soil temperatures at different depths
dataset2_nonempty = dataset2_filtered.drop("FM2_mean_wind_speed_2m_m_s", axis=1)
dataset2_nonempty.drop(["TJM1_soil_temperature_1cm_c", "TJM5_soil_temperature_5cm_c", "TJM30_soil_temperature_30cm_c", "TJM50_soil_temperature_50cm_c",
                        "TJM100_soil_temperature_100cm_c", "SS_snowfall_cm", "PPP_air_pressure__2m_hPa"], axis=1, inplace=True)
missing_values_new = dataset2_nonempty.isna().sum()
missing_values_new

Year                             0
Month                            0
Day                              0
Station                          0
TM_mean_air_temperature_2m_c     0
TN_min_air_temperature_2m_c      0
TX_max_air_temperature_2m_c      0
UM_realtiWe_humudity_%           0
RR_precipitation_mm              0
Q0_global_radiation_MJ_m^2       0
TJM10_soil_temperature_10cm_c    0
TJM20_soil_temperature_20cm_c    0
EPP_evaporation_mm               0
dtype: int64

In [122]:
dataset2_nonempty

,Year,Month,Day,Station,TM_mean_air_temperature_2m_c,TN_min_air_temperature_2m_c,TX_max_air_temperature_2m_c,UM_realtiWe_humudity_%,RR_precipitation_mm,Q0_global_radiation_MJ_m^2,TJM10_soil_temperature_10cm_c,TJM20_soil_temperature_20cm_c,EPP_evaporation_mm
59,2018,3,1,Apelsvoll,-18.1,-22.1,-12.7,67.4,0.0,9.5,0.2,0.5,0.0
60,2018,3,2,Apelsvoll,-13.5,-20.6,-9.6,65.8,0.0,4.9,0.2,0.5,0.0
61,2018,3,3,Apelsvoll,-8.8,-11.0,-4.2,72.8,0.0,4.3,0.2,0.5,0.0
62,2018,3,4,Apelsvoll,-8.0,-10.4,-2.6,79.2,0.4,6.1,0.1,0.5,0.0
63,2018,3,5,Apelsvoll,-7.6,-9.3,-5.1,88.8,2.0,2.7,0.1,0.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97890,2022,9,26,Valnesfjord,11.7,9.5,13.4,61.8,0.5,4.5,9.7,10.0,1.4
97891,2022,9,27,Valnesfjord,10.2,7.0,12.9,64.1,-0.2,7.2,8.9,9.5,1.3
97892,2022,9,28,Valnesfjord,9.6,4.8,13.6,68.7,-0.1,7.5,8.5,9.0,1.0
97893,2022,9,29,Valnesfjord,10.2,8.0,13.0,65.7,0.0,4.6,8.7,9.0,0.8
97894,2022,9,30,Valnesfjord,6.8,1.8,10.5,67.8,0.0,7.1,7.8,8.6,0.9

In [123]:
# Export nonempty dataset to excel for recording
dataset2_nonempty.to_csv("data/IMT_stations_nonempty.csv")