# Predicting the Soil Temperature at 100cm depth using machine learning
### 1. Problem definition
> Soil temperature is one of the important parameters of a soil characteristics that contributes information in understanding the nitrate levels of a soil at different depths. This is because the soil temperature affects the soil's microbial activity, plant uptake, volatilization of Nitrogen compounds and leaching.  NMBU measures soil temperature at different depths (2cm, 5cm, 10cm, 20cm, 50cm, 100cm) using platinum resistance thermometers called PT100. Machine learning based predication may help reducing the effort and installation cost required to measure temperature at deeper soil levels such 100cm. It may also help in calibrating the AgriSenze N-N concentration sensor measurement at different depths. This machine learning algorithm will first try to predict the soil temperature at 100cm from the different data features. 
### 2. Data Source
> To start the analysis process, the data source (2018-2022) is downloaded from the Meteorological data for Ås - BIOKLIM website (https://www.nmbu.no/forskning/grupper/meteorologiske-data) and organized into one big dataset which contains nearly 1800 samples. The improvements will be: first, the dataset will be improved to have bigger number of samples (2000-2024); second, multi-sites will be considererd to make the prediction more generic for different types of soils in Norway.
> #### There is one dataset inside the data folder

### 3. Evaluation metrics
> The evaluation metrics of R-squared (R²) Score, Mean Absolute Error (MAE), Mean Square Error (MSE) and Root Mean Square Error (RMSE) will be considered as common regression metrics.
> > The goal of this machine learning model is to build a machine leanrning model that minimizes the erros: MAE, MSE, RMSE and increase the R-squared (R²) Score.
### 4. Data Features
> The features of the dataset are:  month,	date, mean_air_temperature_2m, min_air_temperature_2m,	max_air_temperature_2m	soil_temperature_2cm,	soil_temperature_5cm,	soil_temperature_10cm,	soil_temperature_20cm,	soil_temperature_50cm,	relative_humudity_%,	air_pressure__2m_mbar,	radiation_balance_w_m2,	albedo_RR_GR,	earth_heat_flux_MJ_m2,	evaporation_mm,	rainfall_mm,	snowfall_cm.
>> The data is inside the data folder in this project.

## 1. Data Preprocessing Step

In [107]:
# Import the necessary python libraries such as pandas, numpy, matplotlib, scikit-learn for data analysis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Regression of the Soil Temperature at depth of 100cm

## Step 1: Getting the data ready for the machine learning modelling

### Main data cleaning and preprocessing activities
### 1. Reading the dataset from file using pandas function
### 2. Split the dataset in to features (independent variable) and labels(dependent variable)
### 3. Imputing (filling) or disregarding missing values depending on the feature or label type
### 4. Encoding or converting non-numerical values to numeric values if required ( Feature encoding)
### 5. Reduce data if it is heavy for the machine to process

In [108]:
# 1. Get the data from the original csv file from data folder
dataset = pd.read_csv("data/NMBUDatasetFinal.csv")
dataset

,year,month,day,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,...,mean_wind_speed_10m_m_s,max_wind_speed_10_m_s,wind_direction_10m,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm,target_soil_temperature_100cm
0,2018,1,1,3.2,0.7,4.4,-0.1,0.1,0.1,0.5,...,2.6,4.7,S,0.13,0.45,-0.12,NaN,2.3,5.0,2.9
1,2018,1,2,-1.9,-5.7,1.4,0.0,0.1,0.1,0.5,...,NaN,NaN,NaN,-1.67,0.32,-0.13,NaN,0.0,3.0,2.9
2,2018,1,3,-0.4,-6.4,1.3,-0.1,0.1,0.1,0.5,...,NaN,NaN,NaN,-0.98,0.43,-0.23,NaN,3.4,3.0,2.9
3,2018,1,4,0.7,0.2,1.1,0.0,0.1,0.1,0.5,...,4.1,5.4,N,-1.31,0.59,-0.12,NaN,2.5,4.0,2.9
4,2018,1,5,-1.8,-5.5,0.1,0.0,0.1,0.1,0.5,...,3.9,5.7,N,-1.65,0.71,-0.11,NaN,1.4,5.0,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,2022,12,27,-1.7,-8.2,1.0,-0.1,0.2,0.1,0.4,...,2.4,5.7,S,-2.06,0.44,-0.29,NaN,0.0,9.0,3.6
1822,2022,12,28,-5.5,-8.9,-4.1,0.0,0.2,0.1,0.5,...,2.0,3.8,N,-1.05,0.88,-0.32,NaN,0.5,9.0,3.5
1823,2022,12,29,0.7,-4.4,4.1,-0.1,0.1,0.1,0.5,...,2.7,6.9,S,-1.23,0.70,-0.33,NaN,8.3,12.0,3.5
1824,2022,12,30,2.7,0.3,4.5,-0.1,0.1,0.1,0.5,...,4.2,8.6,S,-1.66,0.59,-0.31,NaN,6.6,6.0,3.4
1825,2022,12,31,3.0,-3.2,5.6,0.0,0.2,0.1,0.5,...,5.4,11.8,S,-4.34,0.26,-0.27,NaN,4.9,1.0,3.4

In [109]:
len(dataset)

1826

In [110]:
# Check rows with empty values
rows_with_empty_values = dataset[dataset.isna().any(axis=1)]
rows_with_empty_values

,year,month,day,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,...,mean_wind_speed_10m_m_s,max_wind_speed_10_m_s,wind_direction_10m,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm,target_soil_temperature_100cm
0,2018,1,1,3.2,0.7,4.4,-0.1,0.1,0.1,0.5,...,2.6,4.7,S,0.13,0.45,-0.12,NaN,2.3,5.0,2.9
1,2018,1,2,-1.9,-5.7,1.4,0.0,0.1,0.1,0.5,...,NaN,NaN,NaN,-1.67,0.32,-0.13,NaN,0.0,3.0,2.9
2,2018,1,3,-0.4,-6.4,1.3,-0.1,0.1,0.1,0.5,...,NaN,NaN,NaN,-0.98,0.43,-0.23,NaN,3.4,3.0,2.9
3,2018,1,4,0.7,0.2,1.1,0.0,0.1,0.1,0.5,...,4.1,5.4,N,-1.31,0.59,-0.12,NaN,2.5,4.0,2.9
4,2018,1,5,-1.8,-5.5,0.1,0.0,0.1,0.1,0.5,...,3.9,5.7,N,-1.65,0.71,-0.11,NaN,1.4,5.0,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,2022,12,27,-1.7,-8.2,1.0,-0.1,0.2,0.1,0.4,...,2.4,5.7,S,-2.06,0.44,-0.29,NaN,0.0,9.0,3.6
1822,2022,12,28,-5.5,-8.9,-4.1,0.0,0.2,0.1,0.5,...,2.0,3.8,N,-1.05,0.88,-0.32,NaN,0.5,9.0,3.5
1823,2022,12,29,0.7,-4.4,4.1,-0.1,0.1,0.1,0.5,...,2.7,6.9,S,-1.23,0.70,-0.33,NaN,8.3,12.0,3.5
1824,2022,12,30,2.7,0.3,4.5,-0.1,0.1,0.1,0.5,...,4.2,8.6,S,-1.66,0.59,-0.31,NaN,6.6,6.0,3.4
1825,2022,12,31,3.0,-3.2,5.6,0.0,0.2,0.1,0.5,...,5.4,11.8,S,-4.34,0.26,-0.27,NaN,4.9,1.0,3.4

In [111]:
# Check rows with non-empty values throughout its columns
rows_with_non_empty_values = dataset[dataset.notna().all(axis=1)]
rows_with_non_empty_values

,year,month,day,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,...,mean_wind_speed_10m_m_s,max_wind_speed_10_m_s,wind_direction_10m,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm,target_soil_temperature_100cm
123,2018,5,4,7.5,0.2,13.7,7.5,7.3,6.8,6.4,...,2.4,5.7,S,6.89,0.21,0.98,0.3,0.0,0.0,4.2
124,2018,5,5,11.5,6.3,17.8,9.5,8.9,8.1,7.1,...,3.3,6.7,S,9.69,0.22,1.75,1.4,0.0,0.0,4.3
125,2018,5,6,12.3,6.6,18.0,10.1,9.7,9.0,8.0,...,3.8,7.1,S,8.62,0.22,1.27,2.7,0.0,0.0,4.5
126,2018,5,7,12.9,5.7,19.5,10.4,10.0,9.4,8.5,...,2.9,5.7,S,8.51,0.22,1.17,2.5,0.0,0.0,4.7
127,2018,5,8,14.4,7.7,21.0,11.2,10.7,10.0,9.0,...,2.4,7.1,S,9.95,0.23,1.44,3.1,0.0,0.0,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1739,2022,10,6,11.1,8.6,14.6,10.8,10.9,10.8,10.8,...,4.4,8.3,SW,-0.36,0.22,-0.37,1.6,0.0,0.0,10.9
1740,2022,10,7,12.1,9.9,14.9,10.7,10.8,10.6,10.7,...,5.9,9.2,S,-0.55,0.19,0.03,1.6,3.6,0.0,10.9
1741,2022,10,8,9.2,4.6,13.4,9.9,10.3,10.3,10.6,...,2.6,4.8,W,-0.08,0.25,-0.74,1.9,0.0,0.0,10.9
1742,2022,10,9,8.5,1.5,13.5,8.9,9.2,9.3,10.0,...,3.6,7.8,S,1.07,0.25,-0.56,1.1,0.5,0.0,10.9
1743,2022,10,10,10.2,3.8,12.6,9.9,10.0,9.9,10.0,...,4.4,7.5,S,-0.49,0.19,-0.15,0.5,0.9,0.0,10.9

In [112]:
dataset.dtypes

year                               int64
month                              int64
day                                int64
mean_air_temperature_2m          float64
min_air_temperature_2m           float64
max_air_temperature_2m           float64
soil_temperature_2cm             float64
soil_temperature_5cm             float64
soil_temperature_10cm            float64
soil_temperature_20cm            float64
soil_temperature_50cm            float64
relative_humidity_%              float64
air_pressure__2m_mbar            float64
mean_wind_speed_10m_m_s          float64
max_wind_speed_10_m_s             object
wind_direction_10m                object
radiation_balance_w_m2           float64
albedo_RR_GR                     float64
earth_heat_flux_MJ_m2            float64
evaporation_mm                   float64
rainfall_mm                      float64
snowfall_cm                      float64
target_soil_temperature_100cm    float64
dtype: object

In [113]:
# 3. Filling or disregarding missing values 
# First check the missing columns and the number of missing values in each column
missing_values = dataset.isna().sum()
missing_values

year                                0
month                               0
day                                 0
mean_air_temperature_2m             0
min_air_temperature_2m              0
max_air_temperature_2m              0
soil_temperature_2cm                7
soil_temperature_5cm                5
soil_temperature_10cm               5
soil_temperature_20cm               5
soil_temperature_50cm               5
relative_humidity_%                23
air_pressure__2m_mbar               5
mean_wind_speed_10m_m_s            57
max_wind_speed_10_m_s              42
wind_direction_10m                 43
radiation_balance_w_m2              5
albedo_RR_GR                       28
earth_heat_flux_MJ_m2              19
evaporation_mm                   1013
rainfall_mm                         4
snowfall_cm                       542
target_soil_temperature_100cm       5
dtype: int64

### The missing values of the snowfall are in all seasons edatasetcept winter so we can fill them zero
### The missing values of the evaporation are due to the measurement not taken from November to March in winter, so we can fill them by zero.
### The few missing values on soil temperatures at different depth are due to missing measurements and a mean approdatasetimate value can be taken
### The few missing values on relative humidity, air pressure, radiation, heat fludataset and rainfall are due to missing measurements and mean value can be taken
### Fill empty values by either the average value or zero depending on the feature type

In [114]:
# 3. Filling or disregarding missing values contd'

dataset["evaporation_mm"] = dataset["evaporation_mm"].fillna(0.0)
dataset["soil_temperature_2cm"] = dataset["soil_temperature_2cm"].fillna(dataset["soil_temperature_2cm"].mean())
dataset["soil_temperature_5cm"] = dataset["soil_temperature_5cm"].fillna(dataset["soil_temperature_5cm"].mean())
dataset["soil_temperature_10cm"] = dataset["soil_temperature_10cm"].fillna(dataset["soil_temperature_10cm"].mean())
dataset["soil_temperature_20cm"] = dataset["soil_temperature_20cm"].fillna(dataset["soil_temperature_20cm"].mean())
dataset["soil_temperature_20cm"] = dataset["soil_temperature_20cm"].fillna(dataset["soil_temperature_20cm"].mean())
dataset["soil_temperature_50cm"] = dataset["soil_temperature_50cm"].fillna(dataset["soil_temperature_50cm"].mean())
dataset["target_soil_temperature_100cm"] = dataset["target_soil_temperature_100cm"].fillna(dataset["target_soil_temperature_100cm"].mean())
dataset["relative_humidity_%"] = dataset["relative_humidity_%"].fillna(dataset["relative_humidity_%"].mean())
dataset["air_pressure__2m_mbar"] = dataset["air_pressure__2m_mbar"].fillna(dataset["air_pressure__2m_mbar"].mean())
dataset["radiation_balance_w_m2"] = dataset["radiation_balance_w_m2"].fillna(dataset["radiation_balance_w_m2"].mean())
dataset["albedo_RR_GR"] = dataset["albedo_RR_GR"].fillna(dataset["albedo_RR_GR"].mean())
dataset["earth_heat_flux_MJ_m2"] = dataset["earth_heat_flux_MJ_m2"].fillna(dataset["earth_heat_flux_MJ_m2"].mean())
dataset["rainfall_mm"] = dataset["rainfall_mm"].fillna(dataset["rainfall_mm"].mean())
dataset["snowfall_cm"] = dataset["snowfall_cm"].fillna(0.0)

In [115]:
# Check missing values on the features after filling or disregarding values
dataset.isna().sum()

year                              0
month                             0
day                               0
mean_air_temperature_2m           0
min_air_temperature_2m            0
max_air_temperature_2m            0
soil_temperature_2cm              0
soil_temperature_5cm              0
soil_temperature_10cm             0
soil_temperature_20cm             0
soil_temperature_50cm             0
relative_humidity_%               0
air_pressure__2m_mbar             0
mean_wind_speed_10m_m_s          57
max_wind_speed_10_m_s            42
wind_direction_10m               43
radiation_balance_w_m2            0
albedo_RR_GR                      0
earth_heat_flux_MJ_m2             0
evaporation_mm                    0
rainfall_mm                       0
snowfall_cm                       0
target_soil_temperature_100cm     0
dtype: int64

In [116]:
# Remove the unnecessary columns from the features dataset
columns_to_drop = ['mean_wind_speed_10m_m_s', 'max_wind_speed_10_m_s', 'wind_direction_10m']  # List of column names to drop
dataset.drop(columns=columns_to_drop, axis=1, inplace=True)
dataset

,year,month,day,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,soil_temperature_50cm,relative_humidity_%,air_pressure__2m_mbar,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm,target_soil_temperature_100cm
0,2018,1,1,3.2,0.7,4.4,-0.1,0.1,0.1,0.5,1.3,100.0,972.3,0.13,0.45,-0.12,0.0,2.3,5.0,2.9
1,2018,1,2,-1.9,-5.7,1.4,0.0,0.1,0.1,0.5,1.3,100.0,982.1,-1.67,0.32,-0.13,0.0,0.0,3.0,2.9
2,2018,1,3,-0.4,-6.4,1.3,-0.1,0.1,0.1,0.5,1.3,99.0,978.0,-0.98,0.43,-0.23,0.0,3.4,3.0,2.9
3,2018,1,4,0.7,0.2,1.1,0.0,0.1,0.1,0.5,1.3,96.0,978.8,-1.31,0.59,-0.12,0.0,2.5,4.0,2.9
4,2018,1,5,-1.8,-5.5,0.1,0.0,0.1,0.1,0.5,1.3,86.0,982.0,-1.65,0.71,-0.11,0.0,1.4,5.0,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,2022,12,27,-1.7,-8.2,1.0,-0.1,0.2,0.1,0.4,1.4,86.0,990.6,-2.06,0.44,-0.29,0.0,0.0,9.0,3.6
1822,2022,12,28,-5.5,-8.9,-4.1,0.0,0.2,0.1,0.5,1.4,90.0,992.0,-1.05,0.88,-0.32,0.0,0.5,9.0,3.5
1823,2022,12,29,0.7,-4.4,4.1,-0.1,0.1,0.1,0.5,1.4,95.0,975.3,-1.23,0.70,-0.33,0.0,8.3,12.0,3.5
1824,2022,12,30,2.7,0.3,4.5,-0.1,0.1,0.1,0.5,1.4,92.0,979.9,-1.66,0.59,-0.31,0.0,6.6,6.0,3.4
1825,2022,12,31,3.0,-3.2,5.6,0.0,0.2,0.1,0.5,1.4,83.0,975.9,-4.34,0.26,-0.27,0.0,4.9,1.0,3.4

In [117]:
# 2. Split the dataset in to features (independent variables) and labels(dependent variable = target_soil_temperature_100cm )
X = dataset.drop("target_soil_temperature_100cm", axis =1) # Features
Y = dataset["target_soil_temperature_100cm"]

In [118]:
# 5. Encoding non-numeric values
# The only non-numeric value in our dataset is the Wind Direction but it is already removed in the previous steps
# as it is not critical parameter for soil temperature estimation but if required use the following code to
# convert it to degress
# Change the wind direction from N/NE/E/SE/S/SW/W/NW to 0/45/90/135/180/225/270/315 degress

# dataset.loc[dataset['wind_direction_10m'] == 'N', 'wind_direction_10m'] = 0
# dataset.loc[dataset['wind_direction_10m'] == 'NE', 'wind_direction_10m'] = 45
# dataset.loc[dataset['wind_direction_10m'] == 'E', 'wind_direction_10m'] = 90
# dataset.loc[dataset['wind_direction_10m'] == 'SE', 'wind_direction_10m'] = 135
# dataset.loc[dataset['wind_direction_10m'] == 'S', 'wind_direction_10m'] = 180
# dataset.loc[dataset['wind_direction_10m'] == 'SW', 'wind_direction_10m'] = 225
# dataset.loc[dataset['wind_direction_10m'] == 'W', 'wind_direction_10m'] = 270
# dataset.loc[dataset['wind_direction_10m'] == 'NW', 'wind_direction_10m'] = 315

# We could also use OneHotEncoder from sklealrn
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer
# categorical_features = ["wind_direction_10m", "wind_speed_m_s"]
# one_hot = OneHotEncoder()
# transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)]
#                                remainder ="passthrough")
# transformed_dataset = transformer.fit_transform()
# pd.DataFrame(transformed_dataset)

In [119]:
# Split the feature and label datasets in to 80/20 training and test datasets respectively
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

# Step 2. Modelling

## By using sklearn's 'choosing the right estimator' map guidance to choose a model, our number of samples are less 100K and We can check the following sklearn models
1. RidgeRegression
2. SVR(kernel='linear')
3. EnsembleRegressors e.g. RandomForestRegressor
4. SVR(kernel='rbf')
5. Lasso
6. ElasticNet

![Estimator Selection sklearn map](images/sklearn_map.png)

## i. Ridge Model

In [88]:
# Import the model
from sklearn.linear_model import Ridge
# Setup random seed
np.random.seed(10)
# Instantiate and fit the model (on training set)
model = Ridge()
model.fit(X_train, Y_train)
# Check the score of the model (on the test set)
model.score(X_test, Y_test)

0.9777054972875755

## ii. RandomForestRegressor Model data.

In [89]:
# Let's try another model which is ensemble RandomForestRegressor
# Import the model
from sklearn.ensemble import RandomForestRegressor
# Set up a radom seed
np.random.seed(10)
# Create rando forest model
model = RandomForestRegressor()
model.fit(X_train, Y_train)

# Check the score of R^2 coefficient of determination
model.score(X_test, Y_test)

0.9968630336012995

## iii. Lasso Model

In [90]:
# Let's check the Lasso model
# Import the model
from sklearn.linear_model import Lasso
# Set up a radom seed
np.random.seed(10)
# Create rando forest model
model = Lasso()
model.fit(X_train, Y_train)

# Check the score of R^2 coefficient of determination
model.score(X_test, Y_test)

0.9455755017163789

## iv. ElasticNet Model

In [91]:
# Let's check the ElasticNet model
# Import the model
from sklearn.linear_model import ElasticNet
# Set up a radom seed
np.random.seed(10)
# Create rando forest model
model = ElasticNet()
model.fit(X_train, Y_train)

# Check the score of R^2 coefficient of determination
model.score(X_test, Y_test)

0.9530392701778293

## v. SVR with kernel 'linear' model

In [92]:
# Let's check the SVR with kernel linear model
# Import the model
from sklearn.svm import SVR
# Set up a radom seed
np.random.seed(10)
# Create rando forest model
model = SVR(kernel='linear')
model.fit(X_train, Y_train)

# Check the score of R^2 coefficient of determination
model.score(X_test, Y_test)

0.9138870437877219

## vi. SVR with kernel 'rbf' model

In [93]:
# Let's check the SVR with kernel 'rbf' model
# Import the model
from sklearn.svm import SVR
# Set up a radom seed
np.random.seed(10)
# Create rando forest model
model = SVR(kernel='rbf')
model.fit(X_train, Y_train)

# Check the score of R^2 coefficient of determination
model.score(X_test, Y_test)

0.07285908727453871

## Results Analysis
### Ridge Model.
### The negative value of the Ridge regression indicates either of the following reasons
#### a. Overfitting: The model has learned noise in the training data rather than capturing the underlying patterns.
#### b. Underfitting: The model is too simple to capture the underlying patterns in the data
#### c. Data quality: There may be issues with the quality or representativeness of the training data
#### d. Model selection: The chosen model or hyperparameters may not be appropriate for the data

### RandomForestRegressor Ensemble model
### The R^2 score seems good but we need to check the following points further.
#### a. Cross-Validation: Perform cross-validation to evaluate the model's performance on multiple splits of the data. This helps assess how well the model generalizes to unseen data and provides more robust performance estimates.
#### b. Residual Analysis: Edatasetamine the residuals (the differences between actual and predicted values) to check for patterns or systematic errors. Plotting the residuals against predicted values or input features can help identify areas where the model may be inaccurate.
#### c. Feature Importance: Investigate the importance of different features in the model. RandomForestRegressor provides feature importance scores, which can help identify the most influential features in making predictions. Ensure that the important features align with domain knowledge and edatasetpectations.
#### d. Outlier Detection: Check for outliers in the data that may be influencing the model's predictions. Outliers can have a disproportionate impact on regression models and may need to be addressed or removed.

### The R^2 score seems good but we need to check the following points further.

# Step 3. Predicting

In [94]:
# Let's conside the RandomForestRegressor modelling
# Import the model
from sklearn.ensemble import RandomForestRegressor
# Set up a radom seed
np.random.seed(10)
# Create rando forest model
model = RandomForestRegressor()
model.fit(X_train, Y_train)

# Check the score of R^2 coefficient of determination
model.score(X_test, Y_test)

0.9968630336012995

In [95]:
# Make the prediction on the X_test data
Y_preds = model.predict(X_test)

In [96]:
# Check the similarities of the predicted target values and the test target values 
# if they are in a similar representation
Y_preds[:10]

array([13.615, 12.016, 14.218,  6.063,  7.416, 12.878,  3.719, 14.111,
       12.979, 12.93 ])

In [97]:
np.array(Y_test[:10])

array([14. , 12.3, 14.3,  6.1,  7.4, 12.9,  3.6, 14.4, 13. , 13.1])

In [98]:
print(len(Y_test), len(Y_preds))

366 366

#### The MAE results shows that we have ±0.17 celsius from the the actual value of the target (soil temperature at 100cm )

# Step 4. Evaluating the quality of the model predictions

 ## Evaluating the model with the score method (R^2 = coefficient of determination)

In [99]:
model.score(X_test, Y_test)

0.9968630336012995

In [100]:
X_test

,year,month,day,mean_air_temperature_2m,min_air_temperature_2m,max_air_temperature_2m,soil_temperature_2cm,soil_temperature_5cm,soil_temperature_10cm,soil_temperature_20cm,soil_temperature_50cm,relative_humidity_%,air_pressure__2m_mbar,radiation_balance_w_m2,albedo_RR_GR,earth_heat_flux_MJ_m2,evaporation_mm,rainfall_mm,snowfall_cm
611,2019,9,4,10.5,5.9,14.8,13.7,14.1,14.2,14.7,14.8,99.0,994.3,-0.26,0.21,-0.83,2.8,35.5,0.0
1366,2021,9,28,13.0,10.6,16.7,12.6,12.5,13.7,11.9,11.7,92.0,1006.5,2.26,0.23,0.35,1.2,5.1,0.0
577,2019,8,1,17.7,13.1,22.9,18.7,18.5,18.0,17.6,16.6,69.0,1006.2,11.29,0.22,0.84,8.2,0.0,0.0
866,2020,5,16,6.4,0.6,9.7,6.6,6.8,6.6,6.7,6.5,47.0,992.4,-3.56,0.26,-0.28,3.0,0.0,0.0
1422,2021,11,23,0.8,-4.0,5.2,1.1,1.7,2.1,3.2,5.3,92.0,1004.1,-1.74,0.27,-1.23,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,2020,6,26,21.0,14.6,26.5,20.2,19.9,19.3,18.4,15.9,69.0,1007.2,14.10,0.22,0.94,5.5,0.0,0.0
588,2019,8,12,17.0,14.3,20.2,17.3,17.2,16.9,16.5,15.6,90.0,990.1,7.03,0.20,0.33,4.1,0.3,0.0
125,2018,5,6,12.3,6.6,18.0,10.1,9.7,9.0,8.0,6.0,76.0,1011.6,8.62,0.22,1.27,2.7,0.0,0.0
256,2018,9,14,12.3,9.6,15.9,12.6,12.8,12.7,12.9,13.1,78.0,996.5,2.87,0.21,-0.17,2.4,0.3,0.0
1375,2021,10,7,11.3,8.3,13.5,11.6,11.8,12.5,11.9,12.0,94.0,1012.6,1.39,0.20,-0.05,0.6,0.0,0.0

### a. Evaluating the model with cross-validation
#### The cross validation score will evaluate the model by taking K-number of folds or splits for the entire dataset. Let's take K = CV = 10 for this test as the dataset is not big enough. This helps us avoid lucky splits in case we consider only one random split pattern.

In [101]:
from sklearn.model_selection import cross_val_score
np.random.seed(10)
cross_val_score_r2 = cross_val_score(model, X, Y, cv=10)
cross_val_score_r2

array([0.98630588, 0.98404558, 0.98778762, 0.97900301, 0.96975493,
       0.97023501, 0.99131719, 0.98088949, 0.98759721, 0.99074607])

#### Compare the single score and the mean of cross-validation scores
##### The higher the value of the Negative CV MAE or MSE the better the model performance is because for neg_mean_absolute_error and neg_mean_squared_error the value should be higher while for MAE and MSE the value should be lower

In [102]:
np.random.seed(10)
# Single training and test split score
model_single_score = model.score(X_test, Y_test)
# Mean of the 10-fold cross validation score
mean_cross_val_score_r2 = np.mean(cross_val_score(model, X, Y, cv=10))
# Compare the two scores
print("Single Score: ", model_single_score, "Cross Val Score: ", mean_cross_val_score_r2)

Single Score:  0.9968630336012995 Cross Val Score:  0.9827681992703544

In [103]:
# Mean Absolute Error cross validation
np.random.seed(10)
cv_mae = cross_val_score(model, X, Y, cv=10, scoring="neg_mean_absolute_error")
print("Mean CV MAE:", np.mean(cv_mae))
cv_mae

Mean CV MAE: -0.3267435011783798

array([-0.33065574, -0.34810039, -0.24680328, -0.38159087, -0.40801639,
       -0.40628172, -0.27002198, -0.35004424, -0.2819011 , -0.2440193 ])

#### b. R^2 score coefficient of determination
##### If our model was to predict mean value of target variable the R^2 score would be zero then our prediction is accurate and if the predicted value and the test value are the same then the R^2 score value is 1.

In [104]:
from sklearn.metrics import r2_score
# Let's fill an array with Y_test mean
Y_test_mean = np.full(len(Y_test), Y_test.mean())
Y_test_mean[:10]

array([7.49380842, 7.49380842, 7.49380842, 7.49380842, 7.49380842,
       7.49380842, 7.49380842, 7.49380842, 7.49380842, 7.49380842])

In [105]:
# Let us see if the predicted value was the mean value of the target
r2_score(y_true=Y_test, y_pred=Y_test_mean)

0.0

In [106]:
# Let us see if the predicted value was the Y_test value
r2_score(y_true=Y_test, y_pred=Y_test)

1.0

#### c. Mean Absolute Error (MAE)
##### MAE is the average of the absolute differences between the predictions and actual values. It gives us an idea of how wrong our model predictions are.

In [33]:
# Evaluate using MAE
from sklearn.metrics import mean_absolute_error
Y_preds = model.predict(X_test)
mae = mean_absolute_error(Y_test, Y_preds)
mae

0.1751825649751085

In [34]:
df = pd.DataFrame(data={"actual values":Y_test, "predicted values":Y_preds})
df["differences"] = df["predicted values"] - df["actual values"]
df.head(10)

      actual values  predicted values  differences
1676           13.2         13.227000     0.027000
357             4.0          3.931000    -0.069000
861             6.1          6.072000    -0.028000
529            10.2          9.504000    -0.696000
1333           13.5         13.577000     0.077000
1535            1.7          1.736000     0.036000
795             2.6          2.577000    -0.023000
1419            7.7          7.927678     0.227678
754             3.4          3.274000    -0.126000
555            12.3         12.474000     0.174000

In [35]:
# We can also check the MAE by using the formula for MAE calculation
np.abs(df["differences"]).mean()

0.1751825649751085

##### If we see the percentage of the error calculated using the MAE we can divide the MAE by the mean of the Y_test values and multiply by 100

In [36]:
perencentage_error = mae/Y_test.mean() 
print(perencentage_error, "%")

0.023899805791235153 %

#### d. Mean Squared Error (MSE)
##### MSE is the mean of the square of the errors between the actual and predicted values. The MSE should be as low as possible becuase it shows the mean of the square of the difference between the actual values and predicted values

In [37]:
# Evaluate using MSE
from sklearn.metrics import mean_squared_error
Y_preds = model.predict(X_test)
mse = mean_squared_error(Y_test, Y_preds)
mse

0.06298994273245176

In [38]:
df["squared differences"] = np.square(df["differences"])
df.head()

      actual values  predicted values  differences  squared differences
1676           13.2            13.227        0.027             0.000729
357             4.0             3.931       -0.069             0.004761
861             6.1             6.072       -0.028             0.000784
529            10.2             9.504       -0.696             0.484416
1333           13.5            13.577        0.077             0.005929

In [39]:
squared = np.square(df["differences"])
squared.mean()

0.06298994273245176

#### e. Evaluating using the scoring parameter

In [40]:
from sklearn.model_selection import cross_val_score
np.random.seed(10)

In [41]:
# Mean Squared Error cross validation
np.random.seed(10)
cv_mse = cross_val_score(model, X, Y, cv=10, scoring="neg_mean_squared_error")
print("Mean CV MSE:", np.mean(cv_mse))
cv_mse

Mean CV MSE: -0.18948090937341136

array([-0.16762478, -0.19210218, -0.12211582, -0.31351454, -0.26420807,
       -0.27658505, -0.09731399, -0.26109126, -0.11402129, -0.08623211])

#### f. Scikit-Learn evaluation functions
#### Let us check some of the evaluation functions of sklearn
#### i. r2_score
#### ii. mean_absolute_error
#### iii. mean_squared_error
#### iv.  mean_squared_log_error
#### v. mean_absolute_percentage_error
#### vi. median_absolute_error
#### vii. max_error
#### viii. explained_variance_score

In [42]:
# Import the functions
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, mean_squared_log_error, mean_absolute_percentage_error, median_absolute_error, max_error, explained_variance_score

np.random.seed(10)
r2 = r2_score(Y_test, Y_preds)
mean_abs_err = mean_absolute_error(Y_test, Y_preds)
mean_sqr_err =mean_squared_error(Y_test, Y_preds)
mean_sqr_lg_err = mean_squared_log_error(Y_test, Y_preds)
mean_abs_per_err = mean_absolute_percentage_error(Y_test, Y_preds)
median_abs_err = median_absolute_error(Y_test, Y_preds)
max_err = max_error(Y_test, Y_preds)
var_edatasetp_err = explained_variance_score(Y_test, Y_preds)
print("mean_absolute_error: ",mean_abs_err)
print("mean_squared_error: ",mean_sqr_err)
print("mean_squared_log_error: ",mean_sqr_lg_err)
print("mean_absolute_percentage_error: ",mean_abs_per_err)
print("median_abs_err: ",median_abs_err)
print("max_err: ",max_err)
print("Mean of Target: ", Y_test.mean())
print("var_edatasetp_err: ",var_edatasetp_err)

mean_absolute_error:  0.1751825649751085
mean_squared_error:  0.06298994273245176
mean_squared_log_error:  0.001089017893919819
mean_absolute_percentage_error:  0.029108031642911245
median_abs_err:  0.11550000000000271
max_err:  1.088999999999995
Mean of Target:  7.329873995852876
var_edatasetp_err:  0.9964849748957134

# Step 5. Improving our model
### We can look for the following options
#### a. Can we collect more data? (Yes)
#### b. Is a better model we could use? (From sklearn library let us check the possible models)
#### c. Could we improve the RandomForestRegressor to make it better? (Yes - check for Hyperparameter tuning)

#### Hyperparameter Tuning by hand

In [43]:
# Hyperprameter tuning by hand using validation set
# Let us make three sets: Training, validation and test
np.random.seed(10)
# Let us shuffle the entire dataset so that it is randomly arranged
dataset_shuffled = dataset.sample(frac=1)
# Split the dataset into X and Y
X = dataset_shuffled.drop("target_soil_temperature_100cm", axis=1)
Y = dataset_shuffled["target_soil_temperature_100cm"]
# Then split into train, validation and test sets
train_split = round(0.7*len(dataset_shuffled)) # 70% for train set
valid_split = round(train_split + 0.15*len(dataset_shuffled))
X_train, Y_train = X[:train_split], Y[:train_split]
X_valid, Y_valid =X[train_split:valid_split], Y[train_split:valid_split]
X_test, Y_test = X[valid_split:], Y[valid_split:]
model.fit(X_train, Y_train)
# Baseline prediction
Y_preds = model.predict(X_test)

#### Hyperparameter tuning using GridSearchCV
##### NB: This may take time so be patient

In [44]:
# from sklearn.model_selection import GridSearchCV

# # Define the parameter grid to search
# param_grid = {
#     'n_estimators': [100, 200, 300],
#     'max_depth': [None, 10, 20],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4],
#     'max_features': ['sqrt', 'log2', None],
#     'bootstrap': [True, False]
# }

# # Perform Grid Search with cross-validation
# grid_search = GridSearchCV(estimator=model, param_grid=param_grid, 
#                            cv=5, n_jobs=-1, verbose=2)

# # Fit the Grid Search to the data
# grid_search.fit(X_train, Y_train)

# # Get the best parameters and best score
# best_params = grid_search.best_params_
# best_score = grid_search.best_score_

# print("Best Parameters:", best_params)
# print("Best Score:", best_score)

# Step 6. Saving and loading a trained model

#### a. Using Pickle module

In [45]:
# Save the model you created to file
import pickle
pickle.dump(model, open("models/model_Temperature_100cm.pkl", "wb"))

In [46]:
# Load the saved model
loaded_pickle_model = pickle.load(open("models/model_Temperature_100cm.pkl", "rb"))

In [47]:
# Check the score
loaded_pickle_model.score(X_test, Y_test)

0.9960499717544533

In [48]:
# Check if the model loaded works
pickle_Y_preds = loaded_pickle_model.predict(X_test)
pickle_Y_preds

array([ 9.155     ,  5.281     , 12.952     , 13.989     ,  8.10537177,
        4.082     ,  6.203     ,  9.191     , 12.488     ,  2.171     ,
        2.989     ,  2.008     ,  3.383     ,  4.644     ,  5.849     ,
       12.025     ,  8.161     ,  3.455     ,  5.858     , 14.039     ,
        8.068     , 12.512     ,  2.768     ,  9.318     ,  1.999     ,
       10.714     ,  2.396     , 10.353     ,  3.207     , 13.833     ,
       12.953     ,  9.097     ,  4.054     ,  6.544     ,  8.167     ,
        8.417     ,  3.854     ,  3.78      ,  3.424     ,  2.517     ,
        3.096     ,  9.634     ,  6.92      ,  3.775     ,  3.356     ,
        4.296     ,  1.763     ,  2.024     , 10.949     ,  6.716     ,
       13.476     ,  5.542     , 14.222     , 10.413     ,  2.038     ,
        2.453     ,  7.31      ,  1.809     , 11.788     , 12.505     ,
        1.772     , 12.518     ,  7.506     ,  6.261     ,  3.231     ,
       11.753     ,  2.526     , 10.023     , 13.678     ,  2.96      ,
        1.702     ,  2.229     , 10.752     , 13.17      ,  3.084     ,
        1.446     ,  4.726     , 12.569     , 11.179     , 12.815     ,
        3.457     ,  9.001     , 12.849     ,  8.984     ,  6.957     ,
        1.997     , 13.968     , 12.544     ,  3.67      ,  2.167     ,
        7.29      , 12.206     ,  2.088     ,  6.588     ,  8.09090829,
        7.291     ,  4.517     ,  3.706     , 13.337     ,  5.616     ,
        3.957     ,  3.231     , 14.049     , 12.66      ,  4.235     ,
        1.969     , 12.388     ,  3.034     ,  9.233     ,  5.776     ,
        5.947     ,  7.52      ,  8.011     , 11.373     ,  3.588     ,
       12.584     ,  4.075     ,  2.915     ,  2.068     ,  5.445     ,
       10.631     , 10.954     ,  3.259     ,  2.06      ,  2.99      ,
       14.183     , 11.556     ,  7.234     ,  5.55      ,  1.576     ,
        9.813     ,  2.275     ,  6.217     , 10.747     ,  1.782     ,
       11.466     ,  1.634     ,  5.846     ,  3.176     , 12.965     ,
        4.333     , 13.6       , 10.43      ,  9.605     , 12.603     ,
        5.664     ,  5.234     ,  3.183     , 11.256     ,  3.84      ,
        5.836     ,  1.714     , 12.263     , 12.6       , 12.03      ,
        2.735     ,  1.702     , 11.039     , 13.456     , 11.241     ,
       13.621     ,  4.128     , 12.528     ,  3.227     ,  6.077     ,
        3.292     ,  8.02601647,  3.404     ,  3.683     , 13.703     ,
        3.732     ,  7.946     , 12.377     ,  1.746     ,  1.806     ,
        4.647     ,  3.286     ,  3.19      , 12.38      ,  1.706     ,
        9.08      ,  3.213     , 13.738     , 11.3       ,  7.161     ,
        9.651     ,  9.224     ,  5.775     ,  2.464     ,  3.209     ,
        3.829     , 11.29      ,  3.762     ,  9.656     ,  9.381     ,
        1.715     ,  2.923     ,  9.655     ,  2.018     ,  3.149     ,
        3.244     ,  2.338     ,  3.01      ,  2.575     ,  4.244     ,
        1.512     ,  3.606     , 13.336     ,  8.008     ,  5.862     ,
        4.486     , 11.888     ,  2.409     ,  8.87      ,  2.58      ,
        7.9254871 ,  7.255     ,  3.95      , 13.831     ,  5.468     ,
        3.33      , 14.012     , 12.583     ,  2.086     ,  6.985     ,
        1.56      ,  1.74      , 10.237     ,  3.253     , 11.609     ,
       12.983     ,  9.223     ,  1.621     ,  7.776     , 12.269     ,
        9.322     ,  8.803     ,  2.073     ,  3.278     ,  2.657     ,
        2.589     ,  1.838     ,  5.611     , 12.961     , 13.106     ,
       13.061     ,  4.588     ,  2.313     , 13.921     ,  1.653     ,
        9.731     , 12.838     ,  2.016     ,  2.45      , 13.231     ,
        4.038     ,  1.707     ,  3.244     ,  4.143     ,  6.167     ,
        2.09      ,  5.844     , 12.948     ,  4.129     ,  8.998     ,
        1.775     ,  3.345     ,  1.568     ,  1.593     ,  9.13433882,
       12.991     ,  9.879     ,  1.589     , 13.122     ])

#### b. Using Joblib module
##### NB: Go for Joblib if the data used for modelling is large

In [49]:
from joblib import dump, load
# Save model to file
dump(model, filename="models/model_Temperature_100cm_joblib.joblib");

In [50]:
# Import saved joblib model
loaded_joblib_model = load(filename="models/model_Temperature_100cm_joblib.joblib")

In [51]:
# Check the score and prediction
loaded_joblib_model.score(X_test, Y_test)

0.9960499717544533

In [52]:
loaded_joblib_model.predict(X_test)

array([ 9.155     ,  5.281     , 12.952     , 13.989     ,  8.10537177,
        4.082     ,  6.203     ,  9.191     , 12.488     ,  2.171     ,
        2.989     ,  2.008     ,  3.383     ,  4.644     ,  5.849     ,
       12.025     ,  8.161     ,  3.455     ,  5.858     , 14.039     ,
        8.068     , 12.512     ,  2.768     ,  9.318     ,  1.999     ,
       10.714     ,  2.396     , 10.353     ,  3.207     , 13.833     ,
       12.953     ,  9.097     ,  4.054     ,  6.544     ,  8.167     ,
        8.417     ,  3.854     ,  3.78      ,  3.424     ,  2.517     ,
        3.096     ,  9.634     ,  6.92      ,  3.775     ,  3.356     ,
        4.296     ,  1.763     ,  2.024     , 10.949     ,  6.716     ,
       13.476     ,  5.542     , 14.222     , 10.413     ,  2.038     ,
        2.453     ,  7.31      ,  1.809     , 11.788     , 12.505     ,
        1.772     , 12.518     ,  7.506     ,  6.261     ,  3.231     ,
       11.753     ,  2.526     , 10.023     , 13.678     ,  2.96      ,
        1.702     ,  2.229     , 10.752     , 13.17      ,  3.084     ,
        1.446     ,  4.726     , 12.569     , 11.179     , 12.815     ,
        3.457     ,  9.001     , 12.849     ,  8.984     ,  6.957     ,
        1.997     , 13.968     , 12.544     ,  3.67      ,  2.167     ,
        7.29      , 12.206     ,  2.088     ,  6.588     ,  8.09090829,
        7.291     ,  4.517     ,  3.706     , 13.337     ,  5.616     ,
        3.957     ,  3.231     , 14.049     , 12.66      ,  4.235     ,
        1.969     , 12.388     ,  3.034     ,  9.233     ,  5.776     ,
        5.947     ,  7.52      ,  8.011     , 11.373     ,  3.588     ,
       12.584     ,  4.075     ,  2.915     ,  2.068     ,  5.445     ,
       10.631     , 10.954     ,  3.259     ,  2.06      ,  2.99      ,
       14.183     , 11.556     ,  7.234     ,  5.55      ,  1.576     ,
        9.813     ,  2.275     ,  6.217     , 10.747     ,  1.782     ,
       11.466     ,  1.634     ,  5.846     ,  3.176     , 12.965     ,
        4.333     , 13.6       , 10.43      ,  9.605     , 12.603     ,
        5.664     ,  5.234     ,  3.183     , 11.256     ,  3.84      ,
        5.836     ,  1.714     , 12.263     , 12.6       , 12.03      ,
        2.735     ,  1.702     , 11.039     , 13.456     , 11.241     ,
       13.621     ,  4.128     , 12.528     ,  3.227     ,  6.077     ,
        3.292     ,  8.02601647,  3.404     ,  3.683     , 13.703     ,
        3.732     ,  7.946     , 12.377     ,  1.746     ,  1.806     ,
        4.647     ,  3.286     ,  3.19      , 12.38      ,  1.706     ,
        9.08      ,  3.213     , 13.738     , 11.3       ,  7.161     ,
        9.651     ,  9.224     ,  5.775     ,  2.464     ,  3.209     ,
        3.829     , 11.29      ,  3.762     ,  9.656     ,  9.381     ,
        1.715     ,  2.923     ,  9.655     ,  2.018     ,  3.149     ,
        3.244     ,  2.338     ,  3.01      ,  2.575     ,  4.244     ,
        1.512     ,  3.606     , 13.336     ,  8.008     ,  5.862     ,
        4.486     , 11.888     ,  2.409     ,  8.87      ,  2.58      ,
        7.9254871 ,  7.255     ,  3.95      , 13.831     ,  5.468     ,
        3.33      , 14.012     , 12.583     ,  2.086     ,  6.985     ,
        1.56      ,  1.74      , 10.237     ,  3.253     , 11.609     ,
       12.983     ,  9.223     ,  1.621     ,  7.776     , 12.269     ,
        9.322     ,  8.803     ,  2.073     ,  3.278     ,  2.657     ,
        2.589     ,  1.838     ,  5.611     , 12.961     , 13.106     ,
       13.061     ,  4.588     ,  2.313     , 13.921     ,  1.653     ,
        9.731     , 12.838     ,  2.016     ,  2.45      , 13.231     ,
        4.038     ,  1.707     ,  3.244     ,  4.143     ,  6.167     ,
        2.09      ,  5.844     , 12.948     ,  4.129     ,  8.998     ,
        1.775     ,  3.345     ,  1.568     ,  1.593     ,  9.13433882,
       12.991     ,  9.879     ,  1.589     , 13.122     ])

# Step 7: Putting all the above codes into one code

### Note: The preprocessing of the data should be such that
#### 1. All data should be numerical 
#### 2. There should be no missing value
#### 3. You shouldn't test on data you have used for training
#### 4. Tune using hyperparameters or use cross-validation
#### 5. One best performance metric doesn't guarantee a best model

Steps
1. Fill missing data

The missing values of the following features show that we can take the mean/median values to fill the air_pressure__2m_mbar, radiation_balance_w_m2, albedo_RR_GR, earth_heat_flux_MJ_m2, rainfall_mm missing values because they are few. We can drop the featues mean_wind_speed_10m_m_s, wind_direction_10m from our dataset. The missing values of snowfall and evaporation show that there was no snow or evaporation and are made zero.

Missing values

air_pressure__2m_mbar:               5
mean_wind_speed_10m_m_:s            57
max_wind_speed_10_m:_s              42
wind_direction_:10m                 43
radiation_balance_:w_m2              5
albedo_:RR_GR                       28
earth_heat_flux:_MJ_m2              19
evapora:tion_mm                   1013
rai:nfall_mm                         4
sn:owfall_cm                       542
target_soil_tempera:ture_100

2. Covert data to numbers if required ( No data is in nonnumeric format)
3. Build a model on the datacm       5

In [53]:
# Preprocessing
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Joblib saving and loading library
from joblib import dump, load

# Modelling
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, GridSearchCV

# Setyp random seed
import numpy as np
np.random.seed(10)

# Import data and fill missing values
data = pd.read_csv("data/NMBUDatasetFinal.csv")
data.dropna(subset=["target_soil_temperature_100cm"], inplace=True)

# Remove the unnecessary columns from the features dataset
columns_to_drop = ['mean_wind_speed_10m_m_s', 'max_wind_speed_10_m_s', 'wind_direction_10m']  # List of column names to drop
data.drop(columns=columns_to_drop, axis=1, inplace=True)

# Define different features and transformer pipelines as required
# The evaporation and snowfall should be zero if the values are missing
simple_features = ["evaporation_mm", "snowfall_cm"]
simple_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="constant", fill_value=0.0))
])

# To start with simple manipulation the missing soil temperatures at different depths are filled by mean values but in future improvement 
# the values will be filled by average value of that specific month
mean_features = ["soil_temperature_2cm","soil_temperature_5cm", 
                 "soil_temperature_10cm", "soil_temperature_20cm",
                 "soil_temperature_50cm", "relative_humidity_%",
                 "air_pressure__2m_mbar", "radiation_balance_w_m2",
                 "albedo_RR_GR", "earth_heat_flux_MJ_m2","rainfall_mm"
                ]
mean_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean"))
])

# Set up the preprocessing steps (fill missing values then convert to numbers)
preprocessor = ColumnTransformer(
    transformers = [
        ("simple", simple_transformer, simple_features),
        ("mean", mean_transformer, mean_features)
    ])
# Creating a preprocessing and modelling pipeline
model = Pipeline(steps=[("preprocessor", preprocessor),
                ("model", RandomForestRegressor(random_state=10))])
# Split the data
X = data.drop("target_soil_temperature_100cm", axis=1)
Y = data["target_soil_temperature_100cm"]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Use the GridSearchCV with our regression Pipeline to look for hyperparameter tuning
pipe_grid = {
    "preprocessor__mean__imputer__strategy":["mean","median"],
    "model__n_estimators":[100, 300],
    "model__max_depth":[10, 20],
    "model__max_features":['sqrt', None],
    "model__min_samples_split":[2, 5]    
}
gs_model = GridSearchCV(model, pipe_grid, cv=5, verbose=1)

# Fit and score the model
gs_model.fit(X_train, Y_train)
score = gs_model.score(X_test, Y_test)

# Get the best parameters and best score
best_params = gs_model.best_params_
best_score = gs_model.best_score_

print("R^2 Score: ", score)
print("Best Parameters:", best_params)
print("Best Score:", best_score)

# Save and load the final model to/from file
dump(gs_model, filename="models/gs_model_temperature_100cm_joblib.joblib");
load_gs_model = load(filename="models/gs_model_temperature_100cm_joblib.joblib")

Fitting 5 folds for each of 32 candidates, totalling 160 fits
R^2 Score:  0.9921490119431007
Best Parameters: {'model__max_depth': 20, 'model__max_features': None, 'model__min_samples_split': 2, 'model__n_estimators': 300, 'preprocessor__mean__imputer__strategy': 'median'}
Best Score: 0.9906330517346227